site/salvage_diary/urls.py
"""URLs for the 'salvageDiary'-app"""
from django.urls import path

from . import views

app_name = "salvage_diary"

urlpatterns = [
    path(
        "", views.SalvageDiaryEntryExternalList.as_view(), name="SalvageDiaryEntryList"
    ),
    path(
        "ekstern/<slug:slug>/nytt-innlegg/",
        views.SalvageDiaryEntryExternalCreate.as_view(),
        name="SalvageDiaryEntryExternalCreate",
    ),
    path(
        "ekstern/<int:pk>/rediger/",
        views.SalvageDiaryEntryExternalUpdate.as_view(),
        name="SalvageDiaryEntryUpdateExternal",
    ),
    path(
        "ekstern/<int:pk>/slett/",
        views.SalvageDiaryEntryExternalDelete.as_view(),
        name="SalvageDiaryEntryDeleteExternal",
    ),
    path(
        "intern/",
        views.SalvageDiaryEntryInternalList.as_view(),
        name="SalvageDiaryEntryListInternal",
    ),
    path(
        "intern/nytt-innlegg/",
        views.SalvageDiaryEntryInternalCreate.as_view(),
        name="SalvageDiaryEntryInternalCreate",
    ),
    path(
        "intern/<int:pk>/rediger/",
        views.SalvageDiaryEntryInternalUpdate.as_view(),
        name="SalvageDiaryEntryUpdateInternal",
    ),
    path(
        "intern/<int:pk>/slett/",
        views.SalvageDiaryEntryInternalDelete.as_view(),
        name="SalvageDiaryEntryDeleteInternal",
    ),
    path("maskotar/", views.MascotList.as_view(), name="MascotList"),
    path("maskotar/ny/", views.MascotCreate.as_view(), name="MascotCreate"),
    path(
        "maskotar/<slug:slug>/rediger/",
        views.MascotUpdate.as_view(),
        name="MascotUpdate",
    ),
    path(
        "maskotar/<slug:slug>/slett/", views.MascotDelete.as_view(), name="MascotDelete"
    ),
]

site/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.templatetags.static import static as static_url
from django.urls import include, path, reverse
from django.views.csrf import csrf_failure as default_csrf_failure
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "favicon.ico/",
        RedirectView.as_view(url=static_url("images/favicon.ico"), permanent=True),
    ),
    path("brukarar/", include("accounts.urls")),
    path("", include("authentication.urls")),
    path("sitat/", include("quotes.urls")),
    path("lagertilgjenge/", include("storage.urls")),
    path("hendingar/", include("events.urls")),
    path("", include("dashboard.urls")),
    path("notar/", include("sheetmusic.urls")),
    path("kommentarar/", include("common.comments.urls")),
    path("kontakt/", include("contact.urls")),
    path("repertoar/", include("repertoire.urls")),
    path("buttons/", include("buttons.urls")),
    path("julekalender/", include("advent_calendar.urls")),
    path("instrument/", include("instruments.urls")),
    path("uniformer/", include("uniforms.urls")),
    path("forum/", include("forum.urls")),
    path("avstemmingar/", include("polls.urls")),
    path("fotoarkiv/", include("pictures.urls")),
    path("referat/", include("minutes.urls")),
    path("brygging/", include("brewing.urls")),
    path("brukarfiler/", include("user_files.urls")),
    path("pdfar/", include("common.pdfs.urls")),
    path("bergedagbok/", include("salvage_diary.urls")),
    path("tilbakemeldingar/", include("feedback.urls")),
    path("heder/", include("honor.urls")),
    path("", include("search.urls")),
    path("", include("easter_eggs.urls")),
    path("", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


def handler500(request, template_name="500.html"):
    """We have to override this simple view to get context for the 500-template."""
    return render(request, template_name)


def csrf_failure(request: HttpRequest, reason=""):
    """
    Redirect to the expected URL if the user is trying to log in,
    but has already done so. If not, use the default CSRF failure view.

    The redirect circumvents an issue where the user is presented with
    a "403 Forbidden CSRF verification failed" error when trying to
    log in in a browser tab loaded before logging in in another tab.
    Since the user is already authenticated in this case, it should
    be safe to redirect to the URL the user expects to see. All other CSRF failures
    are met with the default CSRF failure view.

    The redirect does not check the provided credentials. This means that
    the user is redirected no matter what they input in the login form.
    This should be fine, since the user is already authenticated
    and no-one has more than one account.

    The issue is mentioned in the Django documentation here:
    https://docs.djangoproject.com/en/5.0/ref/csrf/#why-might-a-user-encounter-a-csrf-validation-failure-after-logging-in
    """
    if (
        request.path == reverse("login")
        and request.method == "POST"
        and request.user.is_authenticated
    ):
        return HttpResponseRedirect(request.POST.get("next") or "/")
    return default_csrf_failure(request, reason)

site/salvage_diary/forms.py
"""Forms for the 'salvage_diary'-app"""
from accounts.models import UserCustom
from common.forms.widgets import (
    AutocompleteSelect,
    AutocompleteSelectMultiple,
    DateDateInput,
)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import HiddenInput, ModelForm

from salvage_diary.models import (
    Mascot,
    SalvageDiaryEntryExternal,
    SalvageDiaryEntryInternal,
)


class MascotForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit("submit", "Legg inn"))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["creators"].queryset = UserCustom.objects.exclude(
            membership_status=UserCustom.MembershipStatus.INACTIVE
        )

    class Meta:
        model = Mascot
        fields = [
            "name",
            "image",
            "creation_start_date",
            "creation_end_date",
            "creators",
            "note",
        ]
        widgets = {
            "creators": AutocompleteSelectMultiple,
            "creation_start_date": DateDateInput,
            "creation_end_date": DateDateInput,
        }


class SalvageDiaryEntryExternalForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit("submit", "Legg inn"))

    def __init__(self, mascot, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial["mascot"] = mascot
        self.fields["mascot"].disabled = True

    class Meta:
        model = SalvageDiaryEntryExternal
        fields = ["title", "thieves", "event", "image", "story", "mascot"]
        widgets = {
            "mascot": HiddenInput,
        }


class SalvageDiaryEntryExternalUpdateForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit("submit", "Legg inn"))

    class Meta:
        model = SalvageDiaryEntryExternal
        fields = ["title", "thieves", "event", "image", "story"]


class SalvageDiaryEntryInternalForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit("submit", "Legg inn"))

    class Meta:
        model = SalvageDiaryEntryInternal
        fields = ["title", "item", "thieves", "users", "event", "image", "story"]
        widgets = {
            "event": AutocompleteSelect,
            "users": AutocompleteSelectMultiple,
        }

site/salvage_diary/views.py
from common.breadcrumbs.breadcrumbs import Breadcrumb, BreadcrumbsMixin
from common.forms.views import DeleteViewCustom
from common.mixins import PermissionOrCreatedMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from .forms import (
    MascotForm,
    SalvageDiaryEntryExternalForm,
    SalvageDiaryEntryExternalUpdateForm,
    SalvageDiaryEntryInternalForm,
)
from .models import Mascot, SalvageDiaryEntryExternal, SalvageDiaryEntryInternal


class MascotList(BreadcrumbsMixin, ListView):
    model = Mascot
    context_object_name = "mascots"
    queryset = Mascot.objects.order_by("name")

    @classmethod
    def get_breadcrumb(cls, **kwargs):
        return Breadcrumb(reverse("salvage_diary:MascotList"), "Maskot")


class MascotCreate(
    LoginRequiredMixin, SuccessMessageMixin, BreadcrumbsMixin, CreateView
):
    model = Mascot
    form_class = MascotForm
    template_name = "common/forms/form.html"
    success_message = "Maskoten blei laga"
    permission_required = "salvage_diary.add_mascot"
    breadcrumb_parent = MascotList
    success_url = reverse_lazy("salvage_diary:MascotList")


class MascotUpdate(PermissionOrCreatedMixin, BreadcrumbsMixin, UpdateView):
    model = Mascot
    form_class = MascotForm
    template_name = "common/forms/form.html"
    breadcrumb_parent = MascotList
    success_url = reverse_lazy("salvage_diary:MascotList")

    def has_permission(self):
        user = self.request.user
        return (
            user.has_perm("salvage_diary.change_mascot")
            or self.get_object().creators.filter(username=user.username).exists()
        )


class MascotDelete(PermissionOrCreatedMixin, BreadcrumbsMixin, DeleteViewCustom):
    model = Mascot
    breadcrumb_parent = MascotList
    success_url = reverse_lazy("salvage_diary:MascotList")

    def has_permission(self):
        user = self.request.user
        return (
            user.has_perm("salvage_diary.delete_mascot")
            or self.get_object().creators.filter(username=user.username).exists()
        )


class SalvageDiaryEntryExternalList(BreadcrumbsMixin, ListView):
    template_name = "salvage_diary/salvagediaryentryexternal_list.html"
    model = SalvageDiaryEntryExternal
    context_object_name = "salvageDiaryEntries"
    queryset = SalvageDiaryEntryExternal.objects.order_by("-created").select_related(
        "mascot"
    )
    paginate_by = 10

    @classmethod
    def get_breadcrumb(cls, **kwargs):
        return Breadcrumb(reverse("salvage_diary:SalvageDiaryEntryList"), "Bergedagbok")


class SalvageDiaryEntryExternalCreate(
    SuccessMessageMixin, BreadcrumbsMixin, CreateView
):
    model = SalvageDiaryEntryExternal
    form_class = SalvageDiaryEntryExternalForm
    template_name = "common/forms/form.html"
    success_message = "Bergedagbokinnlegget blei laga!"
    success_url = reverse_lazy("salvage_diary:SalvageDiaryEntryList")
    breadcrumb_parent = SalvageDiaryEntryExternalList

    mascot = None

    def get_mascot(self):
        if not self.mascot:
            self.mascot = get_object_or_404(Mascot, slug=self.kwargs["slug"])
        return self.mascot

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["mascot"] = self.get_mascot()
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs["mascot"] = self.get_mascot()
        return super().get_context_data(**kwargs)


class SalvageDiaryEntryExternalUpdate(
    PermissionOrCreatedMixin, BreadcrumbsMixin, UpdateView
):
    model = SalvageDiaryEntryExternal
    form_class = SalvageDiaryEntryExternalUpdateForm
    template_name = "common/forms/form.html"
    permission_required = "salvage_diary.change_salvagediaryentryexternal"
    breadcrumb_parent = SalvageDiaryEntryExternalList
    success_url = reverse_lazy("salvage_diary:SalvageDiaryEntryList")


class SalvageDiaryEntryExternalDelete(
    PermissionOrCreatedMixin, BreadcrumbsMixin, DeleteViewCustom
):
    model = SalvageDiaryEntryExternal
    permission_required = "salvage_diary.delete_salvagediaryentryexternal"
    breadcrumb_parent = SalvageDiaryEntryExternalList
    success_url = reverse_lazy("salvage_diary:SalvageDiaryEntryList")


class SalvageDiaryEntryInternalList(BreadcrumbsMixin, ListView):
    template_name = "salvage_diary/salvagediaryentryinternal_list.html"
    model = SalvageDiaryEntryInternal
    context_object_name = "salvageDiaryEntries"
    queryset = SalvageDiaryEntryInternal.objects.order_by("-created")
    paginate_by = 10

    @classmethod
    def get_breadcrumb(cls, **kwargs):
        return Breadcrumb(
            reverse("salvage_diary:SalvageDiaryEntryListInternal"), "Bergedagbok"
        )


class SalvageDiaryEntryInternalCreate(
    LoginRequiredMixin, SuccessMessageMixin, BreadcrumbsMixin, CreateView
):
    model = SalvageDiaryEntryInternal
    form_class = SalvageDiaryEntryInternalForm
    template_name = "salvage_diary/salvagediaryentryinternal_form.html"
    success_message = "Bergedagbokinnlegget blei laga!"
    success_url = reverse_lazy("salvage_diary:SalvageDiaryEntryListInternal")
    breadcrumb_parent = SalvageDiaryEntryInternalList


class SalvageDiaryEntryInternalUpdate(
    PermissionOrCreatedMixin, BreadcrumbsMixin, UpdateView
):
    model = SalvageDiaryEntryInternal
    form_class = SalvageDiaryEntryInternalForm
    template_name = "common/forms/form.html"
    permission_required = "salvage_diary.change_salvagediaryentryinternal"
    breadcrumb_parent = SalvageDiaryEntryInternalList
    success_url = reverse_lazy("salvage_diary:SalvageDiaryEntryListInternal")


class SalvageDiaryEntryInternalDelete(
    PermissionOrCreatedMixin, BreadcrumbsMixin, DeleteViewCustom
):
    model = SalvageDiaryEntryInternal
    permission_required = "salvage_diary.delete_salvagediaryentryinternal"
    breadcrumb_parent = SalvageDiaryEntryInternalList
    success_url = reverse_lazy("salvage_diary:SalvageDiaryEntryListInternal")

site/salvage_diary/templates/salvage_diary/mascot_list.html
{% extends "base.html" %}

{% block title_page %} Maskotar {% endblock title_page %}
{% block title_content %} Maskotar {% endblock title_content %}

{% block header %}
    {{ block.super }}
    <ul class="list-inline my-1">
        {% if user.is_authenticated %}
            <li class="list-inline-item"> 
                <a class="btn btn-primary btn-sm my-1" href="{% url 'salvage_diary:MascotCreate' %}">Legg til maskot</a>
            </li>
        {% endif %}
        <li class="list-inline-item">
            <a href="{% url 'salvage_diary:SalvageDiaryEntryList' %}" class="btn btn-secondary btn-sm">Bergedagbok</a>
        </li>
        <li class="list-inline-item">
            <a href="{% url 'salvage_diary:SalvageDiaryEntryListInternal' %}" class="btn btn-secondary btn-sm">Taktlaus-bergingar</a>
        </li>
    </ul>
{% endblock header %}


{% block content %}
    {% if mascots %}
        {% include "salvage_diary/includes/mascot.html" with mascots=mascots %}
    {% else %}
        <p>Ingen maskotar registrert.</p>
    {% endif %}
{% endblock %}

site/salvage_diary/templates/salvage_diary/salvagediaryentry_list.html
{% extends "base.html" %}

{% block title_page %}Bergedagbok{% endblock title_page %}
{% block title_content %}Bergedagbok{% endblock title_content %}


{% block content %}
    {% if salvageDiaryEntries  %}
            {% include "salvage_diary/includes/salvageDiaryEntry.html" with salvageDiaryEntries=salvageDiaryEntries  %}
            {% include "common/includes/pagination.html" with pagination_label="Sitatsida" %}
    {% else %}
        <p>Ingen innlegg registrert.</p>
    {% endif %}
{% endblock %}

site/salvage_diary/templates/salvage_diary/salvagediaryentryexternal_list.html
{% extends "salvage_diary/salvagediaryentry_list.html" %}

{% block title_page %}Bergedagbok{% endblock title_page %}
{% block title_content %}Bergedagbok{% endblock title_content %}

{% block header %}
    {{ block.super }}
    
    <ul class="list-inline my-1">
        <li class="list-inline-item">
            <a class="btn btn-secondary btn-sm my-1" href="{% url 'salvage_diary:MascotList' %}">Maskotar</a>
        </li>
        <li class="list-inline-item"> 
            <a class="btn btn-secondary btn-sm my-1" href="{% url 'salvage_diary:SalvageDiaryEntryListInternal' %}">Taktlaus-bergingar</a>
        </li>
    </ul>
{% endblock header %}

site/salvage_diary/templates/salvage_diary/salvagediaryentryinternal_form.html
{% extends "common/forms/form.html" %}

{% block form %}
    <p> Hugs at denne sida er open for andre utanfor Taktlause, så ikkje legg ut nokon av løyndommane våre, 
        eller bilete du ikkje ville delt med bestemora di. 
        Om det er andre personar i biletet sørg for at du har løyve (tillating) før du lastar opp. </p>
    {{ block.super }}

{% endblock %}

site/salvage_diary/templates/salvage_diary/salvagediaryentryinternal_list.html
{% extends "salvage_diary/salvagediaryentry_list.html" %}

{% block title_page %}Bergedagbok{% endblock title_page %}
{% block title_content %}Bergedagbok{% endblock title_content %}

{% block header %}
    {{ block.super }}

    <ul class="list-inline my-1">
        {% if user.is_authenticated %}
            <li class="list-inline-item"> 
                <a class="btn btn-primary btn-sm my-1" href="{% url 'salvage_diary:SalvageDiaryEntryInternalCreate' %}">Legg inn innlegg</a>
            </li>
        {% endif %}
        <li class="list-inline-item">
            <a class="btn btn-secondary btn-sm my-1" href="{% url 'salvage_diary:SalvageDiaryEntryList' %}">Andre bergingar</a>        
        </li>
        <li class="list-inline-item">
            <a class="btn btn-secondary btn-sm my-1" href="{% url 'salvage_diary:MascotList' %}">Maskotar</a>
        </li>
    </ul>
     
{% endblock header %}