site/minutes/urls.py
from django.urls import path

from . import views

app_name = "minutes"

urlpatterns = [
    path("", views.minutes_list, name="MinutesList"),
    path("kategoriar/", views.minutes_category_list, name="MinutesCategoryList"),
    path(
        "kategoriar/ny/",
        views.minutes_category_create,
        name="MinutesCategoryCreate",
    ),
    path(
        "kategoriar/<slug:slug>/rediger/",
        views.minutes_category_update,
        name="MinutesCategoryUpdate",
    ),
    path(
        "kategoriar/<slug:slug>/slett/",
        views.minutes_category_delete,
        name="MinutesCategoryDelete",
    ),
    path("ny/", views.minutes_create, name="MinutesCreate"),
    path("<slug:slug>/", views.minutes_detail, name="MinutesDetail"),
    path("<slug:slug>/rediger/", views.minutes_update, name="MinutesUpdate"),
    path("<slug:slug>/slett/", views.minutes_delete, name="MinutesDelete"),
]

site/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.templatetags.static import static as static_url
from django.urls import include, path, reverse
from django.views.csrf import csrf_failure as default_csrf_failure
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "favicon.ico/",
        RedirectView.as_view(url=static_url("images/favicon.ico"), permanent=True),
    ),
    path("brukarar/", include("accounts.urls")),
    path("", include("authentication.urls")),
    path("sitat/", include("quotes.urls")),
    path("lagertilgjenge/", include("storage.urls")),
    path("hendingar/", include("events.urls")),
    path("", include("dashboard.urls")),
    path("notar/", include("sheetmusic.urls")),
    path("kommentarar/", include("common.comments.urls")),
    path("kontakt/", include("contact.urls")),
    path("repertoar/", include("repertoire.urls")),
    path("buttons/", include("buttons.urls")),
    path("julekalender/", include("advent_calendar.urls")),
    path("instrument/", include("instruments.urls")),
    path("uniformer/", include("uniforms.urls")),
    path("forum/", include("forum.urls")),
    path("avstemmingar/", include("polls.urls")),
    path("fotoarkiv/", include("pictures.urls")),
    path("referat/", include("minutes.urls")),
    path("brygging/", include("brewing.urls")),
    path("brukarfiler/", include("user_files.urls")),
    path("pdfar/", include("common.pdfs.urls")),
    path("bergedagbok/", include("salvage_diary.urls")),
    path("tilbakemeldingar/", include("feedback.urls")),
    path("heder/", include("honor.urls")),
    path("", include("search.urls")),
    path("", include("easter_eggs.urls")),
    path("", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


def handler500(request, template_name="500.html"):
    """We have to override this simple view to get context for the 500-template."""
    return render(request, template_name)


def csrf_failure(request: HttpRequest, reason=""):
    """
    Redirect to the expected URL if the user is trying to log in,
    but has already done so. If not, use the default CSRF failure view.

    The redirect circumvents an issue where the user is presented with
    a "403 Forbidden CSRF verification failed" error when trying to
    log in in a browser tab loaded before logging in in another tab.
    Since the user is already authenticated in this case, it should
    be safe to redirect to the URL the user expects to see. All other CSRF failures
    are met with the default CSRF failure view.

    The redirect does not check the provided credentials. This means that
    the user is redirected no matter what they input in the login form.
    This should be fine, since the user is already authenticated
    and no-one has more than one account.

    The issue is mentioned in the Django documentation here:
    https://docs.djangoproject.com/en/5.0/ref/csrf/#why-might-a-user-encounter-a-csrf-validation-failure-after-logging-in
    """
    if (
        request.path == reverse("login")
        and request.method == "POST"
        and request.user.is_authenticated
    ):
        return HttpResponseRedirect(request.POST.get("next") or "/")
    return default_csrf_failure(request, reason)

site/minutes/models.py
from autoslug import AutoSlugField
from common.models import ArticleMixin
from django.db.models import (
    RESTRICT,
    CharField,
    DateField,
    FileField,
    ForeignKey,
    Model,
)
from django.urls import reverse


def default_minutes_category():
    return MinutesCategory.objects.get_or_create(name="Ukjent")[0].pk


class MinutesCategory(Model):
    name = CharField(verbose_name="namn", max_length=255, unique=True)
    slug = AutoSlugField(
        verbose_name="lenkjenamn", populate_from="name", editable=True, unique=True
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "referatkategori"
        verbose_name_plural = "referatkategoriar"

    def __str__(self):
        return self.name


class Minutes(ArticleMixin):
    date = DateField("møtedato", help_text="Datoen møtet vart heldt.")
    file = FileField("fil", upload_to="minutes/", default=None, blank=True)
    slug = AutoSlugField(
        verbose_name="lenkjenamn", populate_from="title", editable=True, unique=True
    )
    category = ForeignKey(
        MinutesCategory,
        verbose_name="kategori",
        related_name="minutes",
        on_delete=RESTRICT,
        default=default_minutes_category,
    )

    def get_absolute_url(self):
        return reverse("minutes:MinutesDetail", args=[self.slug])

    class Meta:
        ordering = ["-date"]
        verbose_name = "referat"
        verbose_name_plural = "referat"

site/minutes/forms.py
from common.forms.widgets import AutocompleteSelect
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms import DateInput, ModelForm

from .models import Minutes, MinutesCategory


class MinutesForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit("submit", "Lagre referat"))

    class Meta:
        model = Minutes
        fields = ["title", "category", "date", "content", "file"]
        widgets = {
            "date": DateInput(attrs={"type": "date"}),
            "category": AutocompleteSelect,
        }


class MinutesCategoryForm(ModelForm):
    helper = FormHelper()
    helper.add_input(Submit("submit", "Lagre kategori"))

    class Meta:
        model = MinutesCategory
        fields = ["name"]

site/minutes/views.py
from authentication.decorators import permission_or_created
from common.breadcrumbs.breadcrumbs import (
    breadcrumb,
    breadcrumbs,
)
from common.forms.views import delete_view, simple_create_view, simple_update_view
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse, reverse_lazy

from .forms import MinutesCategoryForm, MinutesForm
from .models import Minutes, MinutesCategory


@login_required
@breadcrumb("Alle referat", reverse_lazy("minutes:MinutesList"))
def minutes_list(request):
    minutes = Minutes.objects.select_related("created_by", "category")
    return TemplateResponse(
        request,
        "minutes/minutes_list.html",
        {"minutes_list": minutes, "categories": MinutesCategory.objects.all()},
    )


@login_required
@breadcrumb(
    lambda minutes: str(minutes),
    lambda minutes: minutes.get_absolute_url(),
    minutes_list,
)
def minutes_detail(request, slug: str):
    minutes = get_object_or_404(Minutes, slug=slug)
    return TemplateResponse(
        request,
        "minutes/minutes_detail.html",
        {"minutes": minutes} | breadcrumbs(minutes_list),
    )


@login_required
def minutes_create(request):
    return simple_create_view(
        request,
        MinutesForm,
        context=breadcrumbs(minutes_list),
    )


def get_minutes_by_slug(_, slug: str):
    return get_object_or_404(Minutes, slug=slug)


@login_required
@permission_or_created("minutes.change_minutes", object_getter=get_minutes_by_slug)
def minutes_update(request, slug: str):
    minutes = get_object_or_404(Minutes, slug=slug)
    return simple_update_view(
        request,
        MinutesForm,
        minutes,
        context=breadcrumbs(minutes_detail, minutes=minutes),
    )


@login_required
@permission_or_created("minutes.delete_minutes", object_getter=get_minutes_by_slug)
def minutes_delete(request, slug: str):
    minutes = get_object_or_404(Minutes, slug=slug)
    return delete_view(
        request,
        minutes,
        reverse("minutes:MinutesList"),
        context=breadcrumbs(minutes_detail, minutes=minutes),
    )


@login_required
@breadcrumb("Kategoriar", reverse_lazy("minutes:MinutesCategoryList"), minutes_list)
def minutes_category_list(request):
    categories = MinutesCategory.objects.all()
    return TemplateResponse(
        request,
        "minutes/minutes_category_list.html",
        {"categories": categories} | breadcrumbs(minutes_list),
    )


@login_required
@permission_required("minutes.add_minutescategory", raise_exception=True)
def minutes_category_create(request):
    return simple_create_view(
        request,
        MinutesCategoryForm,
        success_url=reverse("minutes:MinutesCategoryList"),
        context=breadcrumbs(minutes_category_list),
    )


@login_required
@permission_required("minutes.change_minutescategory", raise_exception=True)
def minutes_category_update(request, slug: str):
    category = get_object_or_404(MinutesCategory, slug=slug)
    return simple_update_view(
        request,
        MinutesCategoryForm,
        category,
        success_url=reverse("minutes:MinutesCategoryList"),
        context=breadcrumbs(minutes_category_list),
    )


@login_required
@permission_required("minutes.delete_minutescategory", raise_exception=True)
def minutes_category_delete(request, slug: str):
    category = get_object_or_404(MinutesCategory, slug=slug)
    return delete_view(
        request,
        category,
        success_url=reverse_lazy("minutes:MinutesCategoryList"),
        context=breadcrumbs(minutes_category_list),
    )

site/minutes/templates/minutes/minutes_category_list.html
{% extends "base.html" %}

{% block title_page %}Referatkategoriar{% endblock title_page %}
{% block title_content %}Referatkategoriar{% endblock title_content %}

{% block header %}
    {{ block.super }}

    {% if perms.category.add_minutescategory %}
    <a class="btn btn-primary btn-sm my-1" href="{% url 'minutes:MinutesCategoryCreate' %}">
        Ny kategori
    </a>
    {% endif %}
{% endblock header %}

{% block content %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Namn</th>
                <th><span class="visually-hidden">Rediger</span></th>
                <th><span class="visually-hidden">Slett</span></th>
            </tr>
        </thead>

        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>

                <td class="text-center">
                    {% if perms.category.change_minutescategory %}
                    <a
                        href="{% url 'minutes:MinutesCategoryUpdate' category.slug %}"
                        class="btn btn-primary btn-sm"
                    >
                        Rediger
                    </a>
                    {% endif %}
                </td>

                <td class="text-center">
                    {% if perms.category.delete_minutescategory %}
                    <a
                        href="{% url 'minutes:MinutesCategoryDelete' category.slug %}"
                        class="btn btn-danger btn-sm"
                    >
                        Slett
                    </a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

site/minutes/templates/minutes/minutes_detail.html
{% extends 'base.html' %}

{% block title_page %}{{ minutes.title }}{% endblock title_page %}
{% block title_content %}{{ minutes.title }}{% endblock title_content %}

{% block header %}
    {{ block.super }}
    {% include "common/includes/created_modified.html" with object=minutes only %}

    <ul class="list-inline">
        {% if perms.minutes.change_minutes or minutes.created_by == request.user %}
        <li class="list-inline-item">
            <a class="btn btn-primary btn-sm" href="{% url 'minutes:MinutesUpdate' minutes.slug %}">
                Rediger
            </a>
        </li>
        {% endif %}

        {% if perms.pictures.delete_minutes or minutes.created_by == request.user %}
        <li class="list-inline-item">
            <a
                href="{% url 'minutes:MinutesDelete' minutes.slug %}"
                class="btn btn-danger btn-sm"
            >
                Slett
            </a>
        </li>
        {% endif %}
    </ul>
{% endblock header %}

{% block content %}
    <dl class="dl-inline">
        <dt>Møtedato</dt>
        <dd>{{ minutes.date }}</dd>
        <dt>Kategori</dt>
        <dd>{{ minutes.category }}</dd>

        {% if minutes.file %}
            <dt>Referatfil</dt>
            {% load utils %}
            <dd><a href="{{ minutes.file.url }}">{{ minutes.file | filename }}</a></dd>
        {% endif %}
    </dl>

    {% load markdown %}
    {{ minutes.content | markdown }}

    {% load comments %}
    {% comment_list minutes %}
{% endblock content %}

site/minutes/templates/minutes/minutes_list.html
{% extends "base.html" %}

{% block title_page %}Referat{% endblock title_page %}
{% block title_content %}Referat{% endblock title_content %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.3/datatables.min.css"/>
{% endblock css %}

{% block header %}
    {{ block.super }}

    <ul class="list-inline my-1">
        <li class="list-inline-item">
            <a class="btn btn-primary btn-sm my-1" href="{% url 'minutes:MinutesCreate' %}">
                Nytt referat
            </a>
        </li>

        <li class="list-inline-item">
            <a class="btn btn-secondary btn-sm my-1" href="{% url 'minutes:MinutesCategoryList' %}">
                Kategoriar
            </a>
        </li>
    </ul>
{% endblock header %}

{% block content %}
<div class="mb-3 col-md-3">
    <label class="form-label" for="select-category">
        Kategori:
    </label>
    <select class="select form-select" id="select-category">
        <option value="">
            Alle
        </option>
        {% for category in categories %}
            <option value="{{ category }}">
                {{ category }}
            </option>
        {% endfor %}
    </select>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="minutes-table">
        <thead>
            <tr>
                <th>Tittel</th>
                <th>Lagt ut av</th>
                <th>Kategori</th>
                <th>Møtedato</th>
            </tr>
        </thead>

        <tbody>
            {% for minutes in minutes_list %}
            <tr>
                <td>
                    <a href="{{ minutes.get_absolute_url }}">
                        {{ minutes.title }}
                    </a>
                </td>

                <td>
                    {% if minutes.created_by %}
                        <a href="{{ minutes.created_by.get_absolute_url }}">
                            {{ minutes.created_by }}
                        </a>
                    {% else %}
                        Ukjent
                    {% endif %}
                </td>

                <td>{{ minutes.category }}</td>

                <td data-order="{{ minutes.date | date:"U" }}">
                    <time datetime="{{ minutes.date | date:"c" }}">
                        {{ minutes.date }}
                    </time>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block js %}
    <script src="https://cdn.datatables.net/v/bs5/jq-3.6.0/dt-1.11.3/datatables.min.js"></script>
    {% load static %}
    <script src="{% static "minutes/minutes_list.js" %}"></script>
{% endblock js %}